name: Test actions-setup-xcode

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Xcode
      uses: ./
      with:
        xcode-version: "10.0"
        apple-id: bot@sinoru.io
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
